# Generated by Django 5.2.8 on 2025-11-28 22:35

from django.db import migrations
import uuid
def update_referral_codes(apps, schema_editor):
    CustomUser = apps.get_model('shop', 'CustomUser')
    for user in CustomUser.objects.all():
        if not user.referral_code:
            unique_id = uuid.uuid4().hex[:8].upper()
            user.referral_code = f"REF{unique_id}"
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_referral_codes),
    ]