# Generated by Django 5.2.8 on 2025-11-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shoe', 'Chaussure'), ('bijoux', 'Bijoux'), ('sac', 'Sac'), ('other', 'Autre')], default='shoe', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
